# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-15 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
