# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='descripcion_rol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
