# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170110_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zona',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
