# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_menu_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='descripcion_rol',
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Rol'),
        ),
    ]
