# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20170124_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cierre',
            field=models.IntegerField(default=0),
        ),
    ]
