# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('UBIGEO', models.CharField(max_length=6)),
                ('CODCCPP', models.CharField(max_length=4)),
                ('ZONA', models.CharField(max_length=5)),
                ('LLAVE_CCPP', models.CharField(max_length=10)),
                ('LLAVE_ZONA', models.CharField(max_length=15)),
                ('ETIQ_ZONA', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'TB_ZONA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id_ambiente', models.AutoField(db_column='id_ambiente', primary_key=True, serialize=False)),
                ('nombre_ambiente', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'AMBIENTE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id_criterio', models.AutoField(db_column='id_criterio', primary_key=True, serialize=False)),
                ('nombre_criterio', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_criterio', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'CRITERIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(db_column='id_curso', primary_key=True, serialize=False)),
                ('cod_curso', models.CharField(blank=True, max_length=3, null=True)),
                ('nombre_curso', models.CharField(blank=True, max_length=100, null=True)),
                ('nota_minima', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CURSO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CursoCriterio',
            fields=[
                ('id_cursocriterio', models.AutoField(db_column='id_cursocriterio', primary_key=True, serialize=False)),
                ('ponderacion', models.IntegerField()),
                ('id_criterio', models.ForeignKey(db_column='id_criterio', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Criterio')),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Curso')),
            ],
            options={
                'db_table': 'CURSO_CRITERIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CursoFuncionario',
            fields=[
                ('id_cursofuncionario', models.AutoField(db_column='id_cursofuncionario', primary_key=True, serialize=False)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Curso')),
            ],
            options={
                'db_table': 'CURSO_FUNCIONARIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CursoLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Curso')),
            ],
            options={
                'db_table': 'CURSO_LOCAL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DirectorioLocal',
            fields=[
                ('id_local', models.AutoField(db_column='id_local', primary_key=True, serialize=False)),
                ('zona', models.CharField(blank=True, max_length=5, null=True)),
                ('nombre_local', models.CharField(blank=True, max_length=300, null=True)),
                ('zona_ubicacion_local', models.CharField(blank=True, max_length=5, null=True)),
                ('tipo_via', models.CharField(blank=True, max_length=300, null=True)),
                ('nombre_via', models.CharField(blank=True, max_length=300, null=True)),
                ('referencia', models.CharField(blank=True, max_length=300, null=True)),
                ('n_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('km_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('mz_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('lote_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('piso_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono_local_fijo', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono_local_celular', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_inicio', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_fin', models.CharField(blank=True, max_length=100, null=True)),
                ('turno_uso_local', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad_local_total', models.IntegerField(blank=True, null=True)),
                ('capacidad_local_usar', models.IntegerField(blank=True, null=True)),
                ('funcionario_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_email', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_celular', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_email', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_celular', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_total_aulas', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_aulas', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_aulas', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_auditorios', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_auditorios', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_auditorios', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_sala', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_sala', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_sala', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_oficina', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_oficina', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_oficina', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_otros', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_otros', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_otros', models.IntegerField(blank=True, null=True)),
                ('especifique_otros', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_total_computo', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_computo', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_computo', models.IntegerField(blank=True, null=True)),
                ('cursos_locales', models.ManyToManyField(related_name='cursos_local', through='capacitacion.CursoLocal', to='capacitacion.Curso')),
                ('id_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curso_directorio', to='capacitacion.Curso')),
            ],
            options={
                'db_table': 'DIRECTORIO_LOCAL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id_etapa', models.AutoField(db_column='id_etapa', primary_key=True, serialize=False)),
                ('cod_etapa', models.CharField(blank=True, max_length=3, null=True)),
                ('nombre_etapa', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ETAPA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.IntegerField(db_column='id_funcionario', primary_key=True, serialize=False)),
                ('id_cargofuncional', models.CharField(blank=True, max_length=3, null=True)),
                ('nombre_funcionario', models.CharField(blank=True, max_length=100, null=True)),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Curso')),
            ],
            options={
                'db_table': 'FUNCIONARIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FuncionariosINEI',
            fields=[
                ('id_per', models.IntegerField(primary_key=True, serialize=False)),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
                ('ape_paterno', models.CharField(blank=True, db_column='ape_paterno', max_length=100, null=True)),
                ('ape_materno', models.CharField(blank=True, db_column='ape_materno', max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, db_column='nombre', max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'FUNCIONARIOS_INEI',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id_instructor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'INSTRUCTOR',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id_local', models.AutoField(db_column='id_local', primary_key=True, serialize=False)),
                ('zona', models.CharField(blank=True, max_length=5, null=True)),
                ('nombre_local', models.CharField(blank=True, max_length=300, null=True)),
                ('zona_ubicacion_local', models.CharField(blank=True, max_length=5, null=True)),
                ('tipo_via', models.CharField(blank=True, max_length=300, null=True)),
                ('nombre_via', models.CharField(blank=True, max_length=300, null=True)),
                ('referencia', models.CharField(blank=True, max_length=300, null=True)),
                ('n_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('km_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('mz_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('lote_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('piso_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono_local_fijo', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono_local_celular', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_inicio', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_fin', models.CharField(blank=True, max_length=100, null=True)),
                ('turno_uso_local', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad_local_total', models.IntegerField(blank=True, null=True)),
                ('capacidad_local_usar', models.IntegerField(blank=True, null=True)),
                ('funcionario_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_email', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_celular', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_email', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_celular', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_total_aulas', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_aulas', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_aulas', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_auditorios', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_auditorios', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_auditorios', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_sala', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_sala', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_sala', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_oficina', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_oficina', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_oficina', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_otros', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_otros', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_otros', models.IntegerField(blank=True, null=True)),
                ('especifique_otros', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_total_computo', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_computo', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_computo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LOCAL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LocalAmbiente',
            fields=[
                ('id_localambiente', models.AutoField(db_column='id_localambiente', primary_key=True, serialize=False)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('n_piso', models.IntegerField(blank=True, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('id_ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Ambiente')),
                ('id_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Local')),
            ],
            options={
                'db_table': 'LOCAL_AMBIENTE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MarcoLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_local', models.CharField(blank=True, max_length=300, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('responsable_nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('responsable_telefono', models.CharField(blank=True, max_length=300, null=True)),
                ('zona', models.CharField(blank=True, max_length=5, null=True)),
                ('mz_direccion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'MARCO_LOCAL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PEA',
            fields=[
                ('id_pea', models.AutoField(db_column='id_pea', primary_key=True, serialize=False)),
                ('id_per', models.CharField(blank=True, max_length=8, null=True)),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
                ('ape_paterno', models.CharField(blank=True, db_column='ape_paterno', max_length=100, null=True)),
                ('ape_materno', models.CharField(blank=True, db_column='ape_materno', max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, db_column='nombre', max_length=100, null=True)),
                ('id_convocatoriacargo', models.CharField(blank=True, db_column='id_convocatoriacargo', max_length=4, null=True)),
                ('zona', models.CharField(blank=True, db_column='zona', max_length=5, null=True)),
                ('contingencia', models.IntegerField(blank=True, null=True)),
                ('baja_estado', models.IntegerField(blank=True, null=True)),
                ('alta_estado', models.IntegerField(blank=True, default=0, null=True)),
                ('apto', models.IntegerField(blank=True, default=0, null=True)),
                ('id_cargofuncional', models.ForeignKey(db_column='id_cargofuncional', on_delete=django.db.models.deletion.CASCADE, related_name='tipofuncionario', to='capacitacion.Funcionario')),
            ],
            options={
                'db_table': 'PEA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PEA_ASISTENCIA',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(blank=True, max_length=20, null=True)),
                ('turno_manana', models.IntegerField(blank=True, null=True)),
                ('turno_tarde', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PEA_ASISTENCIA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PEA_AULA',
            fields=[
                ('id_peaaula', models.AutoField(db_column='id_peaaula', primary_key=True, serialize=False)),
                ('pea_fecha', models.CharField(blank=True, max_length=100, null=True)),
                ('id_instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Instructor')),
                ('id_localambiente', models.ForeignKey(db_column='id_localambiente', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.LocalAmbiente')),
                ('id_pea', models.ForeignKey(db_column='id_pea', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.PEA')),
            ],
            options={
                'db_table': 'PEA_AULA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PEA_CURSOCRITERIO',
            fields=[
                ('id_pea_cursocriterio', models.AutoField(db_column='id_pea_cursocriterio', primary_key=True, serialize=False)),
                ('nota', models.FloatField()),
                ('id_cursocriterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.CursoCriterio')),
                ('id_peaaula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pea_cursocriterios', to='capacitacion.PEA_AULA')),
            ],
            options={
                'db_table': 'PEA_CURSOCRITERIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PeaNotaFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.FloatField()),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Curso')),
                ('id_pea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.PEA')),
            ],
            options={
                'db_table': 'PEA_NOTA_FINAL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('ubigeo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ccdd', models.CharField(blank=True, max_length=2, null=True)),
                ('ccpp', models.CharField(blank=True, max_length=2, null=True)),
                ('ccdi', models.CharField(blank=True, max_length=2, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'MAE_UBIGEO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UbigeoCursoMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('dia', models.CharField(blank=True, max_length=100, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Curso')),
                ('ubigeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Ubigeo')),
            ],
            options={
                'db_table': 'UBIGEO_CURSO_META',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pea_asistencia',
            name='id_peaaula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peaaulas', to='capacitacion.PEA_AULA'),
        ),
        migrations.AddField(
            model_name='pea',
            name='ubigeo',
            field=models.ForeignKey(db_column='ubigeo', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Ubigeo'),
        ),
        migrations.AddField(
            model_name='marcolocal',
            name='ubigeo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Ubigeo'),
        ),
        migrations.AddField(
            model_name='localambiente',
            name='pea',
            field=models.ManyToManyField(through='capacitacion.PEA_AULA', to='capacitacion.PEA'),
        ),
        migrations.AddField(
            model_name='local',
            name='ambientes',
            field=models.ManyToManyField(through='capacitacion.LocalAmbiente', to='capacitacion.Ambiente'),
        ),
        migrations.AddField(
            model_name='local',
            name='curso_local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capacitacion.CursoLocal'),
        ),
        migrations.AddField(
            model_name='local',
            name='id_curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Curso'),
        ),
        migrations.AddField(
            model_name='local',
            name='ubigeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Ubigeo'),
        ),
        migrations.AddField(
            model_name='directoriolocal',
            name='ubigeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Ubigeo'),
        ),
        migrations.AddField(
            model_name='cursolocal',
            name='id_cursolocal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.DirectorioLocal'),
        ),
        migrations.AddField(
            model_name='cursofuncionario',
            name='id_funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Funcionario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='criterios',
            field=models.ManyToManyField(through='capacitacion.CursoCriterio', to='capacitacion.Criterio'),
        ),
        migrations.AddField(
            model_name='curso',
            name='funcionarios',
            field=models.ManyToManyField(through='capacitacion.CursoFuncionario', to='capacitacion.Funcionario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='id_etapa',
            field=models.ForeignKey(db_column='id_etapa', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Etapa'),
        ),
        migrations.AddField(
            model_name='curso',
            name='metas',
            field=models.ManyToManyField(through='capacitacion.UbigeoCursoMeta', to='capacitacion.Ubigeo'),
        ),
        migrations.AlterUniqueTogether(
            name='cursocriterio',
            unique_together=set([('id_curso', 'id_criterio')]),
        ),
    ]
