# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('UBIGEO', models.CharField(max_length=6)),
                ('ZONA', models.CharField(max_length=5)),
                ('LLAVE_CCPP', models.CharField(max_length=10)),
                ('LLAVE_ZONA', models.CharField(max_length=15)),
                ('ETIQ_ZONA', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'TB_ZONA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id_ambiente', models.AutoField(db_column='id_ambiente', primary_key=True, serialize=False)),
                ('nombre_ambiente', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'AMBIENTE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id_criterio', models.AutoField(db_column='id_criterio', primary_key=True, serialize=False)),
                ('nombre_criterio', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_criterio', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'CRITERIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(db_column='id_curso', primary_key=True, serialize=False)),
                ('cod_curso', models.CharField(blank=True, max_length=3, null=True)),
                ('nombre_curso', models.CharField(blank=True, max_length=100, null=True)),
                ('nota_minima', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CURSO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CursoCriterio',
            fields=[
                ('id_cursocriterio', models.AutoField(db_column='id_cursocriterio', primary_key=True, serialize=False)),
                ('ponderacion', models.IntegerField()),
                ('id_criterio', models.ForeignKey(db_column='id_criterio', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Criterio')),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Curso')),
            ],
            options={
                'db_table': 'CURSO_CRITERIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CursoFuncionario',
            fields=[
                ('id_cursofuncionario', models.AutoField(db_column='id_cursofuncionario', primary_key=True, serialize=False)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Curso')),
            ],
            options={
                'db_table': 'CURSO_FUNCIONARIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id_etapa', models.AutoField(db_column='id_etapa', primary_key=True, serialize=False)),
                ('cod_etapa', models.CharField(blank=True, max_length=3, null=True)),
                ('nombre_etapa', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ETAPA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(db_column='id_funcionario', primary_key=True, serialize=False)),
                ('id_cargofuncional', models.CharField(blank=True, max_length=3, null=True)),
                ('nombre_funcionario', models.CharField(blank=True, max_length=100, null=True)),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Curso')),
            ],
            options={
                'db_table': 'FUNCIONARIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id_local', models.AutoField(db_column='id_local', primary_key=True, serialize=False)),
                ('zona', models.CharField(blank=True, max_length=5, null=True)),
                ('nombre_local', models.CharField(blank=True, max_length=300, null=True)),
                ('zona_ubicacion_local', models.CharField(blank=True, max_length=5, null=True)),
                ('tipo_via', models.CharField(blank=True, max_length=300, null=True)),
                ('nombre_via', models.CharField(blank=True, max_length=300, null=True)),
                ('referencia', models.CharField(blank=True, max_length=300, null=True)),
                ('n_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('km_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('mz_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('lote_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('piso_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono_local_fijo', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono_local_celular', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_inicio', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_fin', models.CharField(blank=True, max_length=100, null=True)),
                ('turno_uso_local', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad_local_total', models.IntegerField(blank=True, null=True)),
                ('capacidad_local_disponible', models.IntegerField(blank=True, null=True)),
                ('capacidad_local_usar', models.IntegerField(blank=True, null=True)),
                ('funcionario_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_email', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_celular', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_email', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_celular', models.CharField(blank=True, max_length=100, null=True)),
                ('x', models.CharField(blank=True, max_length=100, null=True)),
                ('y', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_total_aulas', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_aulas', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_aulas', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_auditorios', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_auditorios', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_auditorios', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_sala', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_sala', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_sala', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_oficina', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_oficina', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_oficina', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_otros', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_otros', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_otros', models.IntegerField(blank=True, null=True)),
                ('especifique_otros', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_total_computo', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_computo', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_computo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LOCAL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LocalAmbiente',
            fields=[
                ('id_localambiente', models.AutoField(db_column='id_localambiente', primary_key=True, serialize=False)),
                ('mesas_cant', models.IntegerField(blank=True, null=True)),
                ('sillas_cant', models.IntegerField(blank=True, null=True)),
                ('carpindividuales_cant', models.IntegerField(blank=True, null=True)),
                ('carpbipersonales_cant', models.IntegerField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('n_piso', models.IntegerField(blank=True, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('puerta_chapa', models.IntegerField(blank=True, null=True)),
                ('puerta_pestillocandado', models.IntegerField(blank=True, null=True)),
                ('puerta_notiene', models.IntegerField(blank=True, null=True)),
                ('sshh', models.IntegerField(blank=True, null=True)),
                ('alumbrado_electrico', models.IntegerField(blank=True, null=True)),
                ('pizarra_acrilica', models.IntegerField(blank=True, null=True)),
                ('pizarra_cemento', models.IntegerField(blank=True, null=True)),
                ('proyector', models.IntegerField(blank=True, null=True)),
                ('computadora', models.IntegerField(blank=True, null=True)),
                ('acceso_internet', models.IntegerField(blank=True, null=True)),
                ('aireacondicionado', models.IntegerField(blank=True, null=True)),
                ('ventiladores', models.IntegerField(blank=True, null=True)),
                ('id_ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Ambiente')),
                ('id_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Local')),
            ],
            options={
                'db_table': 'LOCAL_AMBIENTE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PEA',
            fields=[
                ('id_pea', models.AutoField(db_column='id_pea', primary_key=True, serialize=False)),
                ('id_per', models.CharField(blank=True, max_length=8, null=True)),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
                ('ape_paterno', models.CharField(blank=True, db_column='ape_paterno', max_length=100, null=True)),
                ('ape_materno', models.CharField(blank=True, db_column='ape_materno', max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, db_column='nombre', max_length=100, null=True)),
                ('id_convocatoriacargo', models.CharField(blank=True, db_column='id_convocatoriacargo', max_length=4, null=True)),
                ('zona', models.CharField(blank=True, db_column='zona', max_length=5, null=True)),
                ('baja_estado', models.IntegerField(blank=True, null=True)),
                ('id_cargofuncional', models.ForeignKey(db_column='id_cargofuncional', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Funcionario')),
            ],
            options={
                'db_table': 'PEA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PEA_ASISTENCIA',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(blank=True, max_length=20, null=True)),
                ('turno_manana', models.IntegerField(blank=True, null=True)),
                ('turno_tarde', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PEA_ASISTENCIA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PEA_AULA',
            fields=[
                ('id_peaaula', models.AutoField(db_column='id_peaaula', primary_key=True, serialize=False)),
                ('id_localambiente', models.ForeignKey(db_column='id_localambiente', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.LocalAmbiente')),
                ('id_pea', models.ForeignKey(db_column='id_pea', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.PEA')),
            ],
            options={
                'db_table': 'PEA_AULA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PEA_CURSOCRITERIO',
            fields=[
                ('id_pea_cursocriterio', models.AutoField(db_column='id_pea_cursocriterio', primary_key=True, serialize=False)),
                ('nota', models.IntegerField()),
                ('id_cursocriterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.CursoCriterio')),
                ('id_peaaula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.PEA_AULA')),
            ],
            options={
                'db_table': 'PEA_CURSOCRITERIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('ubigeo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ccdd', models.CharField(blank=True, max_length=2, null=True)),
                ('ccpp', models.CharField(blank=True, max_length=2, null=True)),
                ('ccdi', models.CharField(blank=True, max_length=2, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'MAE_UBIGEO',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pea_aula',
            name='pea_notas',
            field=models.ManyToManyField(through='capacitacion.PEA_CURSOCRITERIO', to='capacitacion.CursoCriterio'),
        ),
        migrations.AddField(
            model_name='pea_asistencia',
            name='id_peaaula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peaaulas', to='capacitacion.PEA_AULA'),
        ),
        migrations.AddField(
            model_name='pea',
            name='ubigeo',
            field=models.ForeignKey(db_column='ubigeo', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Ubigeo'),
        ),
        migrations.AddField(
            model_name='localambiente',
            name='pea',
            field=models.ManyToManyField(through='capacitacion.PEA_AULA', to='capacitacion.PEA'),
        ),
        migrations.AddField(
            model_name='local',
            name='ambientes',
            field=models.ManyToManyField(through='capacitacion.LocalAmbiente', to='capacitacion.Ambiente'),
        ),
        migrations.AddField(
            model_name='local',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Curso'),
        ),
        migrations.AddField(
            model_name='local',
            name='ubigeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Ubigeo'),
        ),
        migrations.AddField(
            model_name='cursofuncionario',
            name='id_funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Funcionario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='criterios',
            field=models.ManyToManyField(through='capacitacion.CursoCriterio', to='capacitacion.Criterio'),
        ),
        migrations.AddField(
            model_name='curso',
            name='funcionarios',
            field=models.ManyToManyField(through='capacitacion.CursoFuncionario', to='capacitacion.Funcionario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='id_etapa',
            field=models.ForeignKey(db_column='id_etapa', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Etapa'),
        ),
        migrations.AlterUniqueTogether(
            name='cursocriterio',
            unique_together=set([('id_curso', 'id_criterio')]),
        ),
    ]
