# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcolocal',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='marcolocal',
            name='mz_direccion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='marcolocal',
            name='responsable_nombre',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='marcolocal',
            name='responsable_telefono',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='marcolocal',
            name='zona',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
