# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pea',
            old_name='reserva',
            new_name='contingencia',
        ),
    ]
