# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pea',
            name='reserva',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
