# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peanotafinal',
            name='aprobado',
            field=models.IntegerField(null=True),
        ),
    ]
