# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0002_pea_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pea',
            name='id_cargofuncional',
            field=models.ForeignKey(db_column='id_cargofuncional', on_delete=django.db.models.deletion.CASCADE, related_name='tipofuncionario', to='capacitacion.Funcionario'),
        ),
    ]
