# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0002_auto_20161225_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='pea',
            name='alta_estado',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
