# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0003_pea_alta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pea',
            name='apto',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
