# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0003_auto_20170114_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcolocal',
            name='ubigeo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Ubigeo'),
        ),
    ]
