# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0003_auto_20161212_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pea_aula',
            name='pea_notas',
            field=models.ManyToManyField(related_name='pea_cursocriterios', through='capacitacion.PEA_CURSOCRITERIO', to='capacitacion.CursoCriterio'),
        ),
    ]
