# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0004_pea_apto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pea_aula',
            name='pea_fecha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
