# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0004_auto_20161213_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pea_aula',
            name='pea_notas',
        ),
    ]
