# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0005_remove_pea_aula_pea_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pea_cursocriterio',
            name='id_peaaula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pea_cursocriterios', to='capacitacion.PEA_AULA'),
        ),
    ]
