# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0005_auto_20170116_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubigeocursometa',
            name='dia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
