# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0006_ubigeocursometa_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeaNotaFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.FloatField()),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Curso')),
                ('id_pea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.PEA')),
            ],
            options={
                'db_table': 'PEA_NOTA_FINAL',
                'managed': True,
            },
        ),
    ]
