# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-15 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0006_auto_20161213_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localambiente',
            name='acceso_internet',
        ),
        migrations.RemoveField(
            model_name='localambiente',
            name='aireacondicionado',
        ),
        migrations.RemoveField(
            model_name='localambiente',
            name='alumbrado_electrico',
        ),
        migrations.RemoveField(
            model_name='localambiente',
            name='carpbipersonales_cant',
        ),
        migrations.RemoveField(
            model_name='localambiente',
            name='carpindividuales_cant',
        ),
        migrations.RemoveField(
            model_name='localambiente',
            name='computadora',
        ),
        migrations.RemoveField(
            model_name='localambiente',
            name='mesas_cant',
        ),
        migrations.RemoveField(
            model_name='localambiente',
            name='pizarra_acrilica',
        ),
        migrations.RemoveField(
            model_name='localambiente',
            name='pizarra_cemento',
        ),
        migrations.RemoveField(
            model_name='localambiente',
            name='proyector',
        ),
        migrations.RemoveField(
            model_name='localambiente',
            name='puerta_chapa',
        ),
        migrations.RemoveField(
            model_name='localambiente',
            name='puerta_notiene',
        ),
        migrations.RemoveField(
            model_name='localambiente',
            name='puerta_pestillocandado',
        ),
        migrations.RemoveField(
            model_name='localambiente',
            name='sillas_cant',
        ),
        migrations.RemoveField(
            model_name='localambiente',
            name='sshh',
        ),
        migrations.RemoveField(
            model_name='localambiente',
            name='ventiladores',
        ),
    ]
