# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0007_peanotafinal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorioLocal',
            fields=[
                ('id_local', models.AutoField(db_column='id_local', primary_key=True, serialize=False)),
                ('zona', models.CharField(blank=True, max_length=5, null=True)),
                ('nombre_local', models.CharField(blank=True, max_length=300, null=True)),
                ('zona_ubicacion_local', models.CharField(blank=True, max_length=5, null=True)),
                ('tipo_via', models.CharField(blank=True, max_length=300, null=True)),
                ('nombre_via', models.CharField(blank=True, max_length=300, null=True)),
                ('referencia', models.CharField(blank=True, max_length=300, null=True)),
                ('n_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('km_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('mz_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('lote_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('piso_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono_local_fijo', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono_local_celular', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_inicio', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_fin', models.CharField(blank=True, max_length=100, null=True)),
                ('turno_uso_local', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad_local_total', models.IntegerField(blank=True, null=True)),
                ('capacidad_local_usar', models.IntegerField(blank=True, null=True)),
                ('funcionario_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_email', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_celular', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_email', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_celular', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_total_aulas', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_aulas', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_aulas', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_auditorios', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_auditorios', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_auditorios', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_sala', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_sala', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_sala', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_oficina', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_oficina', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_oficina', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_otros', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_otros', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_otros', models.IntegerField(blank=True, null=True)),
                ('especifique_otros', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_total_computo', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_computo', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_computo', models.IntegerField(blank=True, null=True)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Curso')),
                ('ubigeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Ubigeo')),
            ],
            options={
                'db_table': 'DIRECTORIO_LOCAL',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='local',
            name='marcolocal',
        ),
        migrations.AddField(
            model_name='local',
            name='directorio_local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capacitacion.DirectorioLocal'),
        ),
    ]
