# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0008_auto_20170123_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='marcolocal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capacitacion.MarcoLocal'),
        ),
    ]
