# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0008_auto_20161214_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id_instructor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pea_asistencia',
            name='id_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Instructor'),
        ),
    ]
