# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0009_local_marcolocal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoriolocal',
            name='id_curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Curso'),
        ),
        migrations.AlterField(
            model_name='local',
            name='id_curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Curso'),
        ),
    ]
