# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20170123_0111'),
        ('capacitacion', '0010_auto_20170123_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_directoriolocal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.DirectorioLocal')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
            options={
                'db_table': 'USUARIO_LOCALES',
                'managed': True,
            },
        ),
    ]
