# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0011_auto_20161216_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pea_asistencia',
            name='id_instructor',
        ),
        migrations.AddField(
            model_name='pea_aula',
            name='id_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Instructor'),
        ),
    ]
