# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20170123_0111'),
        ('capacitacion', '0011_usuariolocal'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoriolocal',
            name='usuarios',
            field=models.ManyToManyField(through='capacitacion.UsuarioLocal', to='login.User'),
        ),
    ]
