# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0012_directoriolocal_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='directorio_local',
        ),
        migrations.AddField(
            model_name='local',
            name='usuario_local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capacitacion.UsuarioLocal'),
        ),
    ]
